-- MySQL Script generated by MySQL Workbench
-- Tue Oct 10 18:55:35 2023
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `soturno` DEFAULT CHARACTER SET utf8 ;
USE `soturno` ;

-- -----------------------------------------------------
-- Table `mydb`.`usuarios`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `soturno`.`usuarios` (
  `idUsuario` INT NOT NULL AUTO_INCREMENT,
  `nome` VARCHAR(45) NOT NULL,
  `senha` VARCHAR(45) NOT NULL,
  `email` VARCHAR(250) NOT NULL,
  `tipo` VARCHAR(25) NOT NULL,
  PRIMARY KEY (`idUsuario`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`pocoes`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `soturno`.`pocoes` (
  `idPocoes` INT NOT NULL AUTO_INCREMENT,
  `nome` VARCHAR(45) NOT NULL,
  `preco` DECIMAL(5,2) NOT NULL,
  `criador` VARCHAR(45) NOT NULL,
  `imagem` VARCHAR(100) NOT NULL,
  `tipo` VARCHAR(45) NOT NULL,
  `descricao` VARCHAR(500) NOT NULL,
  `ingredientes` VARCHAR(300) NOT NULL,
  PRIMARY KEY (`idPocoes`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`feiticos`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `soturno`.`feiticos` (
  `idFeiticos` INT NOT NULL AUTO_INCREMENT,
  `nome` VARCHAR(45) NOT NULL,
  `preco` DECIMAL(5,2) NOT NULL,
  `criador` VARCHAR(45) NOT NULL,
  `descricao` VARCHAR(500) NOT NULL,
  PRIMARY KEY (`idFeiticos`))
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
